name: Public API Contract
on:
  pull_request:
    branches: [ work, main ]
  workflow_dispatch:
jobs:
  contract:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install starlette pytest httpx PyJWT
      - name: Run tests
        run: pytest -q tests/public_api
