name: Push Production Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag to publish (for example: v1.2.3 or latest)"
        required: true
        default: latest
      image_name:
        description: "Override the image name (defaults to mcp-agent)"
        required: false
        default: mcp-agent
      runner_labels:
        description: >-
          JSON array of runner labels (for example: ["ubuntu-latest"] or
          ["self-hosted", "linux", "x64"])
        required: false
        default: '["ubuntu-latest"]'

env:
  REGISTRY: ghcr.io

jobs:
  push:
    name: Build and push image
    runs-on: ${{ fromJSON(inputs.runner_labels) }}
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: ${{ github.repository_owner }}/${{ inputs.image_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ inputs.tag }}
            type=sha

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
