name: SBOM and Non-root Check
on:
  pull_request:
    branches: [ work, main ]
  push:
    tags: [ 'agent-v*' ]
  workflow_dispatch:
jobs:
  sbom:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/mcp-agent
          tags: |
            type=ref,event=tag
            type=raw,value=ci
      - name: Build image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            VCS_REF=${{ github.sha }}
            VERSION=${{ github.ref_name }}
            REPO_URL=${{ github.server_url }}/${{ github.repository }}
      - name: Verify non-root
        run: |
          cid=$(docker run -d ${{ steps.meta.outputs.tags }})
          uid=$(docker exec "$cid" id -u)
          docker rm -f "$cid" >/dev/null
          test "$uid" -ne 0
      - name: Generate SBOM (SPDX JSON)
        uses: anchore/sbom-action@v0
        with:
          image: ${{ steps.meta.outputs.tags }}
          output-file: sbom.spdx.json
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-spdx
          path: sbom.spdx.json
