name: Tools Registry
on:
  pull_request:
    branches: [ work, main ]
  workflow_dispatch:
jobs:
  tests:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest httpx pyyaml prometheus_client
      - name: Run registry tests
        run: |
          pytest -q tests/registry
